-- vim.g["fern#default_hidden"] = 1
-- vim.g["fern#show_hidden"] = 1

require('plugin')
require('base')
require('keymap')
require('lsp')
require('lsp-config')
require('statusline')
require('fzf-lua-config')
require('toggleterm-config')
require('neotest-config')
require('dap-config')
require('gittool')
require('notice-config')
require('nvim-web-devicons-config')
require('hlchunk-config')
require('oil-config')
require('formatter')
require('blink-conf')
