-- vim.api.nvim_set_var('loaded_netrw', 1)
-- vim.api.nvim_set_var('loaded_netrwPlugin', 1)
require('plugin')
require('color-schema')
require('base')
require('lsp-config')
require('statusline')
require('telescope-config')
require('toggleterm-config')
require('keymap')
require('neotest-config')
require('cmp-config')
--require('neotest-config')
-- require('tree-config')

