version: '3'

vars:
  IMAGE_NAME: '{{.DOCKERHUB_USER}}/nvim-config'
  TAG: 'latest'

tasks:
  build:
    desc: Docker imageをビルド
    cmds:
      - docker build -t {{.IMAGE_NAME}}:{{.TAG}} .
    sources:
      - Dockerfile
      - '**/*.lua'

  run:
    desc: カレントディレクトリでNeovimを起動
    cmds:
      - >-
        docker run -it --rm
        -v "$(pwd)":/workspace
        -v "$HOME/.gitconfig":/root/.gitconfig:ro
        -v "$HOME/.ssh":/root/.ssh:ro
        {{.IMAGE_NAME}}:{{.TAG}} {{.CLI_ARGS}}

  push:
    desc: Docker Hubにpush
    cmds:
      - docker push {{.IMAGE_NAME}}:{{.TAG}}

  buildx:
    desc: マルチプラットフォームビルド+push (amd64/arm64)
    cmds:
      - >-
        docker buildx build
        --platform linux/amd64,linux/arm64
        -t {{.IMAGE_NAME}}:{{.TAG}}
        --push .

  shell:
    desc: コンテナ内でbashを起動 (デバッグ用)
    cmds:
      - >-
        docker run -it --rm --entrypoint bash
        -v "$(pwd)":/workspace
        -v "$HOME/.gitconfig":/root/.gitconfig:ro
        -v "$HOME/.ssh":/root/.ssh:ro
        {{.IMAGE_NAME}}:{{.TAG}}

  test:
    desc: 全テスト実行
    cmds:
      - eval $(luarocks --lua-version 5.1 path) && busted --lua nlua --helper tests/minimal_init.lua tests/

  test:static:
    desc: 静的テストのみ (パーサー不要)
    cmds:
      - eval $(luarocks --lua-version 5.1 path) && busted --lua nlua tests/lsp_config_spec.lua tests/consistency_spec.lua

  test:docker:
    deps: [build]
    desc: Docker イメージ内でテスト実行
    cmds:
      - >-
        docker run --rm --entrypoint nvim {{.IMAGE_NAME}}:{{.TAG}}
        --headless +"luafile /root/.config/nvim/tests/test_docker_smoke.lua"

  version:
    desc: コンテナ内のNeovimバージョン確認
    cmds:
      - docker run --rm {{.IMAGE_NAME}}:{{.TAG}} --version
