--fern = require('fern')
--
--fern.setup({
--    disable_default_mappings = true,  -- デフォルトのマッピングを無効にするかどうか
--    winopts = {
--        win_height = 10,  -- Fern ウィンドウの高さ
--        win_width = 30,   -- Fern ウィンドウの幅
--        border = 'shadow',  -- ボーダースタイル（'none', 'single', 'double', 'shadow' など）
--    },
--    show_ignored = false,  -- 無視されたファイルを表示しないかどうか
--    show_hidden = true,    -- 隠しファイルを表示するかどうか
--    hide_dot = false,      -- ドットファイルを表示するかどうか
--    previewer = {
--        custom = 'cat',    -- プレビューに使用するコマンドやプラグイン
--    },
--})

--vim.api.nvim_set_keymap('n', '<c-e>', '<cmd>lua require("fern"):toggle()<CR>', { noremap = true, silent = true })
