--require('toggleterm').setup{
--  size = 20,
--  open_mapping = [[<c-\>]],
--  hide_numbers = true,
--  shade_filetypes = {},
--  shade_terminals = true,
--  shading_factor = 2,
--  start_in_insert = true,
--  persist_size = true,
--  direction = 'horizontal'
--}
